-- Q8. Views in SQL
-- a. Create a view named product_category_sales that provides insights into sales performance by product category. This view should include the following information:

-- productLine: The category name of the product (from the ProductLines table).

-- total_sales: The total revenue generated by products within that category (calculated by summing the orderDetails.quantity * orderDetails.priceEach for each product in the category).

-- number_of_orders: The total number of orders containing products from that category.

-- (Hint: Tables to be used: Products, orders, orderdetails and productlines)

-- The view when read should show the output as:

select * from products;
select * from orders;
select * from orderdetails;
select * from productlines;


create view Product_category_sales as(select p.productline , sum(o.quantityOrdered * o.priceEach) as total_sales , count(distinct od.orderNumber) as number_of_orders from products 
join orderdetails o
on o.productCode = products.productCode
join productlines p
on p.productline = products.productline
join orders od
on od.orderNumber = o.orderNumber
group by p.productline);

select * from product_category_sales;
 


